version: '3'
services:
  graphql-demo:
    image: graphql-demo:1.0
    ports:
    - 3000:3000
    depends_on:
    - mongodb
    environment:
    - MONGO_USER=admin
    - MONGO_PASS=password
    - MONGO_DB=graphql
  mongodb:
    image: mongo
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=graphql
    volumes:
    - mongo-graphql-data:/data/db
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-graphql-data:
    driver: local